config/routes.rb
Devcolicious::Application.routes.draw do

  root :to => 'home#index'

  # - Devise Section -
  devise_for :users
  # - End Devise Section -

  # - Bookmarks Section -
  get '/bookmarks/import' => 'bookmarks#import',
      :as => :import_bookmarks
  post '/bookmarks/import/:provider' => 'bookmarks#import_from_provider',
      :as => :import_bookmarks_from_provider
  resources :bookmarks
  # - End Bookmarks Section -

  # - Tags Section -
  resources :tags, :constraints => { :id => /\S+/ }
  # - End Tags Section -

  # - Searches Section -
  post '/searches/bookmarks_by_tag'
  # - End Searches Section -

end

app/models/bookmark.rb
class Bookmark
  include Mongoid::Document
  
  # - Relationships -
  has_and_belongs_to_many :users

  # - Attribute Accessors -
  attr_accessor :dirty_tags

  # - Fields -
  field :url,   type: String
  field :title, type: String
  field :tags,  type: Array

  # - Indexes -
  index :url, unique: true
  index :tags

  # - Validations -
  validate :format_of_url
  validates_presence_of :url

  # - Callbacks -
  before_save :clean_dirty_tags
  before_save :sanitize_tags

  # - Instance Methods -
  def format_of_url
    errors.add :url, "is not a valid" if ( self.url =~ URI::regexp ).nil?
  end

  def users_count
    self.user_ids.size
  end

  def sanitize_tags
    self.tags = self.tags.map( &:downcase ).uniq
  end

  def clean_dirty_tags
    if self.dirty_tags.is_a? String
      self.tags = Bookmark.tags_from_string self.dirty_tags
    end
  end

  # - Class Methods -
  class << self

    def find_by_tags( tags )
      all_in :tags => tags
    end

    def tags_from_string( tags )
      tags.split( ',' ).map { |tag| tag.gsub( ' ', '' ) }
    end

    def from_delicious_feed( user = nil, delicious_username )
      bookmarks = []
      begin
        feed = retrieve_feed_from_delicious delicious_username
        unless feed.is_a? Fixnum
          time = Time.now.utc
          feed.entries.each do |entry|
            bookmark = Bookmark.find_or_initialize_by url: entry.url
            bookmark.title  = entry.title
            bookmark.tags   = entry.categories
            bookmark.users  << user if user
            if bookmark.save
              bookmarks << bookmark
              Tag.cache_tags bookmark, time
            end
          end
        end
      rescue Exception => e
        Rails.logger.error e.message
      end
      bookmarks
    end

    def retrieve_feed_from_delicious( username )
      feed  = nil
      # TODO:                                         Fix this hack  vvvvv
      url = "http://feeds.delicious.com/v2/rss/#{ username }?count=999999"
      begin
        feed = Feedzirra::Feed.fetch_and_parse url
      rescue Exception => e
        Rails.logger.error e.message
      end
      feed
    end

  end

end

app/models/tag.rb
class Tag
  include Mongoid::Document
  include Mongoid::Timestamps

  identity :type => String

  field :name,  :type => String
  field :count, :type => Float, :default => 0.0
  field :used_at, :type => Time

  referenced_in :user

  index :name

  validates_uniqueness_of :name,  :allow_blank => false

  class << self
   def cache_tags(bookmark, at_time)
     if bookmark.is_a? String
       bookmark = Bookmark.find(bookmark)
     end

      tags = bookmark.tags
      existing_tags = Tag.where(:name.in => tags).only(:name).map(&:name)

      if !existing_tags.blank?
        Tag.collection.update({ :name => {:$in => existing_tags}},
                              { :$inc => {:count => 1}, :$set => {:used_at => at_time }},
                              { :multi => true })
      end

      (tags-existing_tags).each do |name|
        Tag.new( {name: name,
                  count: 1,
                  user_id: bookmark.user_ids.first,
                  created_at: at_time,
                  updated_at: at_time,
                  used_at: at_time}).save
      end
   end 
  end


end

app/models/user.rb
class User
  include Mongoid::Document

  # - Relationships -
  has_and_belongs_to_many :bookmarks

  # - Devise -
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # - Instance Methods -
  def bookmarks_count
    self.bookmark_ids.size
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def load_bookmarks
    @bookmarks = Bookmark.all
  end

  def current_tags
    @current_tags ||= if params[:controller] == "tags"
                       (params[:id]||[]).split("+")
                      else
                       (params[:tags]||[]).split("+")
                      end
  end
  helper_method :current_tags

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_filter :authenticate_user!

  def index
    @bookmarks = current_user.bookmarks
    respond_to do |format|
      format.html
      format.json { render :json => @bookmarks }
    end
  end

  def show
    @bookmark = Bookmark.find params[ :id ]
    respond_to do |format|
      format.html
      format.json { render :json => @bookmark }
    end
  end

  def new
    @bookmark = Bookmark.new
    respond_to do |format|
      format.html
      format.json { render :json => @bookmark }
    end
  end

  def create
    @bookmark = Bookmark.create params[ :bookmark ]
    Tag.cache_tags @bookmark, Time.now.utc if @bookmark.persisted?
    respond_to do |format|
      format.html do
        if @bookmark.persisted?
          flash[ :notice ] = 'Bookmark successfully created.'
          redirect_to bookmark_path( @bookmark )
        else
          flash[ :error ] = 'Bookmark could not be saved.'
          render :new
        end
      end
      format.json do
        result = {}
        if @bookmark.persisted?
          result = {
            :status   => 'ok',
            :message  => 'Bookmark successfully created',
            :bookmark => @bookmark
          }
        else
          result = {
            :status   => 'error',
            :message  => 'Bookmark could not be saved.',
            :errors   => @bookmark.errors.full_messages
          }
        end
        render :json => result
      end
    end
  end

  def import
    if request.xhr?
      render :layout => false
    else
      respond_to do |format|
        format.html
        format.json
      end
    end
  end

  def import_from_provider
    provider = params[ :provider ]
    case provider
    when 'delicious'
      Bookmark.from_delicious_feed current_user, params[ :delicious_username ]
    end
    flash[ :notice ] = 'Bookmarks imported successfully.'
    redirect_to bookmarks_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :load_bookmarks, :only => [ :index ]

  def index
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def bookmarks_by_tag
    if params[ :tags ].empty?
      redirect_to root_path and return
    end
    tags = Bookmark.tags_from_string params[ :tags ]
    if current_user
      if params[ :global ]
        @bookmarks = Bookmark.find_by_tags tags
      else
        @bookmarks = current_user.bookmarks.find_by_tags tags
      end
    else
      @bookmarks = Bookmark.find_by_tags tags
    end
    render 'home/index'
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
    if params[:group_by] == "alpha"
      @tags = @tags.order_by(["name", "asc"])
    end

    p "-"*80
    p params[:sort_by] == "counter"
    if params[:sort_by] == "counter"
      @tags = @tags.order_by(["count", "desc"])
    end
    respond_to do |format|
      format.html
    end
  end
  
  def show
    @tag_names = @current_tags = current_tags
    @tags = Tag.where( :name.in => @tag_names )

    @bookmarks = Bookmark.where( :tags.in => @tag_names )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for( object )
    result = ''
    if object.respond_to? :errors and object.errors.any?
      title  = "#{ pluralize( object.errors.count, 'error' ) } prohibited this #{ object.class.name.downcase } from being saved:"
      result << '<div class="error_explanation">\n'
      result << "<h2>#{ title }</h2>\n"
      result << '<ul>\n'
      object.errors.full_messages.each do |message|
        result << "<li>#{ message }</li>\n"
      end
      result << '</ul>\n'
      result << '</div>\n'
    end
    result.html_safe
  end

end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/bookmarks/_bookmark.html.slim
.bookmark
  span.title = link_to bookmark.title || bookmark.url, bookmark_path( bookmark )
  - unless bookmark.tags.empty?
    ul.tags
      - bookmark.tags.each do |tag|
        li
          = link_to tag, tag_path(id: ((current_tags)+[tag]).uniq.join("+")), :rel => "tag"
  .users-count
    = "shared by #{bookmark.users_count} users"

app/views/bookmarks/_form.html.slim
= form_for @bookmark do |f|
  = error_messages_for @bookmark
  fieldset.url_field
    = f.label :url
    = f.text_field :url
  fieldset
    = f.label :title
    = f.text_field :title
  fieldset
    = f.label :tags
    = f.text_field :dirty_tags
    br/
    small
      i Separate tags by commas: ruby, rails, ror, php, mongodb, nosql
  fieldset
    = f.submit

app/views/bookmarks/import.html.slim
= form_tag import_bookmarks_from_provider_path( :delicious ) do
 = label_tag 'Delicious Username'
 br/
 = text_field_tag :delicious_username
 br/
 = submit_tag 'Import'

app/views/bookmarks/index.html.slim
.main-content
  .new-bookmark
    -@bookmark = Bookmark.new
    = render 'bookmarks/form'
  .bookmark-list
    h1 My bookmarks
    - unless @bookmarks.empty?
      - @bookmarks.each do |bookmark|
        = render 'bookmark', bookmark: bookmark
    = link_to 'Back', root_path

.tag-list
  ul.tags
    -Tag.all.each do |tag|
      li
        = link_to tag.name, tag_path(id: ((current_tags)+[tag.name]).uniq.join("+")), :rel => "tag"

app/views/bookmarks/new.html.slim
h1 New bookmark
= render 'form'
= link_to 'Back', root_path

app/views/bookmarks/show.html.slim
' Title:
= @bookmark.title
br/
' URL:
= link_to @bookmark.url, @bookmark.url
br/
' Tags:
= @bookmark.tags.join ', '
br/
' Users count:
= @bookmark.users_count
br/
= link_to 'Back', bookmarks_path

app/views/home/index.html.slim
.main-content
  .new-bookmark
    -@bookmark = Bookmark.new
    = render 'bookmarks/form'

  .bookmark-list
    - unless @bookmarks.empty?
      - @bookmarks.each do |bookmark|
        = render 'bookmarks/bookmark', bookmark: bookmark

.tag-list
  ul.tags
    -Tag.all.each do |tag|
      li
        = link_to tag.name, tag_path(id: ((current_tags)+[tag.name]).uniq.join("+")), :rel => "tag"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devcolicious</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title Devcolicious
    = stylesheet_link_tag 'application'
    /= javascript_include_tag 'jquery.min', 'jquery.colorbox.min', 'application'
    = javascript_include_tag 'jquery.min', 'jquery.colorbox.min', 'global'
    = csrf_meta_tags
  body class=controller_name
    .wrapper
      .header
        = render 'shared/flash_messages'
        - if user_signed_in?
          = current_user.email
          '  |
          = link_to 'My bookmarks', bookmarks_path
          '  |
          = link_to 'New bookmark', new_bookmark_path
          '  |
          = link_to 'Import from Delicious', import_bookmarks_path( :provider => :delicious ), :class => 'ajax-content'
          '  |
          = link_to 'Edit profile', edit_user_registration_path
          '  |
          = link_to 'Sign out', destroy_user_session_path
        - else
          = link_to 'Sign in', new_user_session_path
          '  or
          = link_to 'Sign up', new_user_registration_path
        = render 'shared/search_box'
      .content
        = yield
      .footer

app/views/shared/_flash_messages.html.slim
- flash.each do |type, message|
  div id="flash" class=type = message

app/views/shared/_search_box.html.slim
= form_tag searches_bookmarks_by_tag_path do
  = label_tag 'Search by tags (comma separated) '
  = text_field_tag :tags
  - if user_signed_in?
    = check_box_tag :global, nil, true
    ' Global?
  = submit_tag 'Search'

app/views/tags/_tag.html.slim
span class="tag tag_#{tag}"
  = link_to tag.name, tag_path(id: tag.name), rel: "tag"
span
  b
    = "x #{tag.count.to_i}"

app/views/tags/index.html.slim
.main-content
  - if params[:group_by] == "alpha"
    - @tags.group_by {|tag| tag.name[0]}.each do |letter, letter_tags|
        .tag_group
          .letter
            = letter
          table.tags-table
          - letter_tags.each_slice(4) do |tags|
            tr
              - tags.each do |tag|
                td
                  = render "tag", tag: tag
  - else
    table.tags-table
      - @tags.each_slice(4) do |tags|
        tr
          - tags.each do |tag|
            td
              = render "tag", tag: tag

app/views/tags/show.html.slim
.main-content
  .bookmark-list
    h1= "Bookmarks with #{@tag_names.join(", ")} tags"
    - unless @bookmarks.empty?
      - @bookmarks.each do |bookmark|
        = render 'bookmarks/bookmark', bookmark: bookmark
    = link_to 'Back', :back

.tag-list
  ul.tags
    -Tag.all.each do |tag|
      li
        = link_to tag.name, tag_path(id: ((current_tags)+[tag.name]).uniq.join("+")), :rel => "tag"